name: install common dependencies

description: pull common source and binary dependencies via habitat.

inputs:
  concurrency:
    description: concurrency of requests
    default: '2'
    required: false
  target:
    description: habitat target
    default: ''
    required: false
  target_only:
    description: only install dependencies for the target
    default: 'false'
    required: false
  run-habitat-sync:
    description: whether to run habitat sync
    default: 'true'
    required: false

runs:
  using: composite
  steps:
    - name: run habitat sync
      if: ${{ inputs.run-habitat-sync == 'true' }}
      shell: bash
      working-directory: lynxtron/src
      run: |
        set -x
        if [[ "${{ inputs.target }}" == "" ]]; then
          python3 ${{ github.workspace }}/lynxtron/lynxtron_tools/habitat_lock.py -- ${{ github.workspace }}/lynxtron/lynxtron_tools/hab sync .
        elif [[ "${{ inputs.target_only }}" == "true" ]]; then
          python3 ${{ github.workspace }}/lynxtron/lynxtron_tools/habitat_lock.py -- ${{ github.workspace }}/lynxtron/lynxtron_tools/hab sync . --target ${{ inputs.target }} --target-only
        else
          python3 ${{ github.workspace }}/lynxtron/lynxtron_tools/habitat_lock.py -- ${{ github.workspace }}/lynxtron/lynxtron_tools/hab sync . --target ${{ inputs.target }}
        fi
      env:
        HABITAT_CONCURRENCY: ${{ inputs.concurrency }}
        GIT_LFS_SKIP_SMUDGE: 1
